feat: ag-nchainz start-relayer now starts a single-channel relay

diff --git a/packages/cosmic-swingset/bin/ag-nchainz b/packages/cosmic-swingset/bin/ag-nchainz
--- a/packages/cosmic-swingset/bin/ag-nchainz
+++ b/packages/cosmic-swingset/bin/ag-nchainz
@@ -16,6 +16,11 @@ trap 'kill $(jobs -p) 2>/dev/null' EXIT
 BASE_PORT=8000
 NUM_SOLOS=1
 
+get_alphabetic() {
+  id="$1"
+  ida=$(echo "$1" | sed -e 's/0/zero/g; s/1/one/g; s/2/two/g; s/3/three/g; s/4/four/g; s/5/five/g; s/6/six/g; s/7/seven/g; s/8/eight/g; s/9/nine/g;')
+}
+
 real0=$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")
 thisdir=$(cd "$(dirname -- "$real0")" && pwd -P)
 
@@ -115,6 +120,79 @@ start-solos)
   echo "Waiting for all ${1+"$@ "}solos (Hit Control-C to exit)..."
   wait
   exit 0
+  ;;
+start-relayer)
+  template=$1
+  BASE_RE='([^/]*)\.json$'
+  i=0
+  get_alphabetic $i
+  while [[ -e "nchainz/config/$ida.json" ]]; do
+    i=$(( $i + 1 ))
+    get_alphabetic $i
+  done
+
+  echo "Reading path specification (Control-D to finish, Control-C to abort)..."
+  tmpfile=/tmp/$ida.json.$$
+  trap "rm -f '$tmpfile'" EXIT
+  cat > "$tmpfile"
+
+  cid0=$(jq -r '.[0]["connection-id"]' "$tmpfile")
+  if [[ $cid0 == null ]]; then
+    echo 1>&2 "You must specify .[0][\"connection-id\"]"
+    exit 1
+  fi
+
+  dir0=
+  dir1=
+  for fname in nchainz/config/*.json; do
+    [[ -z $template || $fname == "nchainz/config/$template.json" ]] || continue
+    [[ $fname =~ $BASE_RE ]] || continue
+    if grep -q '"generator": "ag-nchainz"' "$fname"; then :
+    else
+      srccid=$(jq -r '.["src"]["connection-id"]' "$fname")
+      dstcid=$(jq -r '.["dst"]["connection-id"]' "$fname")
+      echo "$srccid:$dstcid $fname"
+      case "$srccid:$dstcid" in
+      $cid0:*)
+        dir0=src dir1=dst
+        template=${BASH_REMATCH[1]}
+        break
+        ;;
+      *:$cid0)
+        dir0=dst dir1=src
+        template=${BASH_REMATCH[1]}
+        break
+        ;;
+      esac
+    fi
+  done
+
+  if [[ -z $dir0 || -z $dir1 ]]; then
+    if [[ -n $template ]]; then
+      echo 1>&2 "Connection ID \`$cid0' is not defined in nchainz/config/$template.json"
+    else
+      echo 1>&2 "Connection ID \`$cid0' is not defined in nchainz/config/*.json"
+    fi
+    exit 1
+  fi
+
+  jq -s ".[0] * { \"$dir0\": .[1][0], \"$dir1\": .[1][1], "'"generator": "ag-nchainz"}' "nchainz/config/$template.json" "$tmpfile" > "nchainz/config/$ida.json"
+
+  echo "$ rly config add-dir nchainz/config/"
+  rly config add-dir nchainz/config/
+
+  path=$ida
+  echo "$ rly start -d $path"
+  rly start -d "$path" &
+  try=0
+  while ! rly tx link $path --timeout=3s -d >> "nchainz/logs/$path.log" 2>&1; do
+    try=$(( $try + 1 ))
+    echo "$path tx link not yet ready (try=$try)"
+    sleep 1
+  done
+  try=$(( $try + 1 ))
+  echo "$path tx link initialized (try=$try)"
+  wait
   ;;
 *)
   echo 1>&2 "$progname: unrecognized command \`$COMMAND'"
